#general settings
show_progress: True
gpu_id: 0
state: INFO
reproducibility: True
use_gpu: True
data_path: 'dataset/YOOCHOOSE'
checkpoint_dir: 'saved'
dataset: yoochoose-clicks

# model config
model: NARM
embedding_size: 50
hidden_size: 100
n_layers: 1
dropout_probs: [0.25,0.5]
loss_type: 'CE'

# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
load_col:
  inter: [session_id, item_id, timestamp]

# training settings
neg_sampling:
epochs: 30
train_batch_size: 1024
learner: adam
learning_rate: 0.001
training_neg_sample_num: 0
eval_step: 1
stopping_step: 10

# evalution settings
eval_args:
  split: {'RS':[8,1,1]}
  group_by: user
  order: TO
  mode: full
metrics: ["Recall", "MRR"]
valid_metric: Recall@20
eval_batch_size: 1024
topk: [20]
group_field: session_id
loss_decimal_place: 4
metric_decimal_place: 4