# Environment settings
show_progress: True
gpu_id: 0
seed: 2022
use_gpu: True
state: INFO
reproducibility: True
data_path: 'dataset'
checkpoint_dir: 'saved'
dataset: ml-1M
save_dataset: True
save_dataloaders: True

# Data settings
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
LABEL_FIELD: rating
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
user_inter_num_interval: "[50,inf)"
sst_attr: "gender"
sst_attr_list: ["gender","age"]
load_col:
  inter: [user_id,item_id,rating,timestamp]
  user: [user_id,gender,age,occupation]

# model config
model: NonParityFair
embedding_size: 2

# training settings
epochs: 30
train_batch_size: 1024
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
weight_decay: 0.001
neg_sampling: ~

# evalution settings
eval_args:
  split: {'RS':[8,1,1]}
  group_by: user
  order: RO
  mode: labeled
metrics: ["RMSE","NonParity"]
valid_metric: RMSE
eval_batch_size: 1024
loss_decimal_place: 4
metric_decimal_place: 4