n_layers: 2
n_heads: 2
hidden_size: 50
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'
train_batch_size: 128
learner: adam
learning_rate: 0.001
metrics: ["NDCG","Hit"]
topk: [10]
stopping_step: 20
neg_sampling:
gpu_id: 0
use_gpu: True
True seed: 2020
state: INFO
reproducibility: True
data_path: 'dataset/YOOCHOOSE'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: True
save_dataloaders: True
MAX_ITEM_LIST_LENGTH: 50
POSITION_FIELD: position_id
USER_ID_FIELD: session_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
valid_metric: NDCG@10
eval_args:
  split: {'LS':'valid_and_test'}
  mode: uni100
  order: 'TO'
item_inter_num_interval: '[5,inf)'
load_col:
  inter: [session_id, item_id, timestamp]