embedding_size: 64
n_layers: 2
LABEL_FIELD: gender
RATING_FIELD: rating
neg_sampling: ~
dis_hidden_size_list: [16,8,2,2]
filter_hidden_size_list: [128,64,64]
metrics: ["RMSE"]
valid_metric: RMSE
learning_rate: 0.005
train_epoch_interval: 5
fair_weight: 0.1
