# Environment settings
show_progress: True
gpu_id: 0
seed: 2022
use_gpu: False
state: INFO
reproducibility: True
data_path: 'dataset'
checkpoint_dir: 'saved'
dataset: ml-1M
save_dataset: True
save_dataloaders: True
save_sst_embed: True

# Data settings
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
user_inter_num_interval: "[4,inf)"
sst_attr_list: ["gender","age","occupation"]
load_col:
  inter: [user_id,item_id]
  user: [user_id,gender,age,occupation]

# model config
model: PFCN_MLP
embedding_size: 64
mlp_hidden_size_list: [64, 32, 16]
dis_hidden_size_list: [128, 256, 128, 128, 64, 32]
activation: leakyrelu
filter_mode: sm
dropout: 0.2
dis_dropout: 0.3

# training settings
epochs: 300
train_batch_size: 4096
learner: adam
learning_rate: 0.001
training_neg_sample_num: 1
train_epoch_interval: 10
eval_step: 5
stopping_step: 10
weight_decay: 0.0001
dis_weight: 10

# evalution settings
eval_args:
  split: {'RS':[8,1,1]}
  group_by: user
  order: RO
  mode: uni100
metrics: ["NDCG","Hit"]
valid_metric: NDCG@5
topk: [5,10,15]
eval_batch_size: 4096
loss_decimal_place: 4
metric_decimal_place: 4