# Environment settings
show_progress: True
gpu_id: 0
seed: 2022
use_gpu: True
state: INFO
reproducibility: True
data_path: 'dataset'
checkpoint_dir: 'saved/saved_FairGo_GCN'
dataset: ml-1M
save_dataset: True
dataset_save_path: ~
save_dataloaders: True
dataloaders_save_path: ~
log_wandb: False
save_sst_embed: True
# pretrain_model_file_path: 'saved/saved_FairGo_GCN/FairGo_GCN-FairGo_ml-1M-pretrain.pth'

# Data settings
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
LABEL_FIELD: rating
threshold: ~
TIME_FIELD: timestamp
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
load_pretrain_weight: False
load_col:
  inter: [user_id,item_id,rating,timestamp]
  user: [user_id,gender,age,occupation]
#   user_emb: [uid,user_emb]
#   item_emb: [iid,item_emb]
# preload_weight: {'uid': user_emb, 'iid':item_emb}
# additional_feat_suffix: [user_emb,item_emb]
# alias_of_user_id: [uid]
# alias_of_item_id: [iid]

# model config
model: FairGo_GCN
sst_attr_list: ['occupation']
aggr_method: 'WAP'
vs_weights: [4,1]
embedding_size: 64
n_layers: 1
dis_hidden_size_list: [16,8,4]
filter_hidden_size_list: [128,64]
activation: leakyrelu
fair_weight: 0.1

# gcn
gcn_n_layers: 1
hidden_channels: 32
gcn_dropout: 0.2
gcn_act: relu

# training settings
pretrain_epochs: 600
epochs: 300
train_batch_size: 6048
learner: adam
learning_rate: 0.005
training_neg_sample_num: ~
neg_sampling: ~
train_epoch_interval: 5
eval_step: 10
stopping_step: 5
weight_decay: 0.0001

# evalution settings
eval_args:
  split: {'RS':[8,1,1]}
  group_by: user
  order: RO
  mode: labeled
metrics: ["RMSE"]
valid_metric: RMSE
eval_batch_size: 1024
loss_decimal_place: 4
metric_decimal_place: 4