# Environment settings
show_progress: True
gpu_id: 0
seed: 2022
use_gpu: True
state: INFO
reproducibility: True
data_path: 'dataset'
checkpoint_dir: 'saved'
dataset: ml-100K
save_dataset: True
save_dataloaders: True

# Data settings
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
item_inter_num_interval: "[35,inf)"
val_interval: {rating: "[3,inf)"}
sst_info:
  user: ["gender"]
load_col:
  inter: [user_id,item_id,rating,timestamp]
  user: [user_id,gender]
sst_attr_list: ["gender"]
rm_dup_inter: last

# model config
model: FATR
embedding_size: 20

# training settings
Lambda: 1
learning_rate: 0.001
training_neg_sample_num: ~
gamma: 0.05
tol: 1e-4

# evalution settings
eval_args:
  split: {'LS':"test_only"}
  group_by: user
  order: TO
  mode: uni100
metrics: ["Precision"]
valid_metric: Precision@15
topk: 15
eval_batch_size: 1024
loss_decimal_place: 4
metric_decimal_place: 4